config/routes.rb
Rails.application.routes.draw do
  get "brag" => "brag#index"
  resources :quests
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

root "quests#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quest.rb
class Quest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/brag_controller.rb
class BragController < ApplicationController
  def index
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: %i[ show edit update destroy ]

  # GET /quests or /quests.json
  def index
    @quests = Quest.all.order(created_at: :desc)
    @new_quest = Quest.new
  end

  # GET /quests/1 or /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests or /quests.json
  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to quests_path, notice: "Quest was successfully created." }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1 or /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: "Quest was successfully updated." }
        format.json { render :show, status: :ok, location: @quest }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@quest, partial: "quests/quest", locals: { quest: @quest }) }
      end
    end
  end

  # DELETE /quests/1 or /quests/1.json
  def destroy
    @quest.destroy!

    respond_to do |format|
      format.html { redirect_to quests_path, status: :see_other, notice: "Quest was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@quest) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quest_params
      params.require(:quest).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brag_helper.rb
module BragHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/brag/index.html.erb
<div class="mx-auto font-sans text-gray-600">
<div class="bg-[#4cad99] text-white p-4 flex items-center">
  <%= link_to root_path, class: "text-2xl mr-4", data: { testid: "back-to-quests-button", turbo: false } do %>
    <i class="fas fa-arrow-left"></i> 
  <% end %>
  <span class="flex-grow text-center text-3xl font-bold">My Brag Document</span> 
</div>

<div class="bg-white pb-5 shadow-md mb-5">
  <div class="relative w-full h-[200px] overflow-hidden">
  <%= image_tag "macbook.JPG", alt: "Banner Image", class: "w-full h-full object-cover" %>
</div>
<div class="bg-gray-50 rounded-2xl p-4 shadow-sm mt-8 md:mx-60 mx-10">

      <h1 class="text-3xl font-bold italic text-center p-5 pt-0 text-gray-600">Goals for 2025</h1>
      <div class="flex flex-row pl-5 w-full h-0.5 rounded-2xl bg-[#4cad99] "></div> 

        <div class="space-y-4">
        <div class="rounded-xl p-5">
            <ul class="space-y-3">
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>สอบ Academy ผ่าน</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>เขียน Logic ของโค้ดได้ด้วยตัวเอง</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>ทำ TDD จนคล่อง</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>เขียน Test จนเซียน</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span class="">มีเรื่องที่ถนัดจนคนอื่นขอความช่วยเหลือได้ (แต่ยังไม่รู้ว่าเรื่องอะไร)</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>มี business context เพื่อเข้าใจลูกค้า</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>เป็นส่วนหนึ่งที่ช่วยทีมได้</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>มีเวลาพอที่จะลงเรียนเพิ่มทักษะ แต่ต้องผ่านเงื่อนไขทำงานด้วยตัวเองให้ได้ก่อน</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>อ่านหนังสือสักเล่ม</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>วิ่งแบบไม่หยุดได้ใน 30 นาที</span>
            </li>
            <li class="flex items-start">
                <span class="inline-block min-w-2 h-2 rounded-full bg-yellow-500 mt-2 mr-3"></span>
                <span>เวทเทรนนิ่งหุ่นกระชับ</span>
            </li>
            </ul>
          </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Academy Quest3" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    
    </main>
  </body>
</html>

app/views/quests/_form.html.erb
<%= form_with(model: quest, class: "contents") do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul class="list-disc ml-6">
        <% quest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": quest.errors[:name].none?, "border-red-400 focus:outline-red-600": quest.errors[:name].any?}] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :status %>
    <%= form.checkbox :status, class: ["block shadow-sm rounded-md border order-first h-5 w-5", {"border-gray-400 focus:outline-blue-600": quest.errors[:status].none?, "border-red-400 focus:outline-red-600": quest.errors[:status].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/quests/_quest.html.erb
<div id="<%= dom_id(quest) %>"
     class="flex items-center justify-between p-4 bg-white rounded-md shadow-sm border border-gray-200"
     data-controller="quest-editor" >

  <div class="flex items-center flex-grow" id="<%= dom_id(quest, :status) %>"> 
    <%= form_with(model: quest, url: quest_path(quest), method: :patch, remote: true, class: "mr-3", data: { controller: "checkbox", checkbox_target: "form" }) do |form| %>
      <%= form.check_box :status,
                          data: { action: "change->checkbox#submitForm" },
                          class: "
                            appearance-none h-6 w-6 border border-yellow-500 rounded-md order-first cursor-pointer
                            
                            flex items-center justify-center
                            checked:bg-yellow-500 checked:border-transparent
                            checked:after:content-['✓']
                            checked:after:text-white checked:after:text-sm
                            checked:after:flex checked:after:items-center checked:after:justify-center
                          ",
                          checked: quest.status
      %>
    <% end %>

  
      <span class="text-gray-800 text-lg <%= 'line-through text-gray-500' if quest.status %>"
            data-quest-editor-target="display"
      >
        <%= quest.name %>
      </span>
    

 
    <%= form_with(model: quest, url: quest_path(quest), method: :patch, remote: true, class: "flex-grow hidden", data: { quest_editor_target: "editForm", action: "submit->quest-editor#submitForm" }) do |form| %>
      <%= form.text_field :name,
                          class: "block shadow-sm rounded-md border px-3 py-2 w-full text-lg focus:outline-none focus:border-gray-500 focus:ring-0",
                          data: { quest_editor_target: "nameField" }
      %>
     
      <div class="flex items-center mt-2"> 
        <button type="submit" class="px-4 py-2 bg-gray-800 text-white rounded-md hover:bg-gray-700 transition duration-200">
          Save
        </button>
       
        <button type="button"
                data-action="quest-editor#cancel"
                class="ml-2 px-4 py-2 bg-gray-300 text-gray-800 rounded-md hover:bg-gray-400 transition duration-200">
          Cancel
        </button>
      </div>
    <% end %>
  </div>

 
  <div class="flex items-center ml-4">
    
    <%# <button type="button"
            data-action="quest-editor#edit"
            class="p-2 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full transition duration-200"
    >
      <i class="fas fa-pencil-alt text-xl"></i>
    </button> %>

   
    <%= button_to quest_path(quest), method: :delete,
                  data: { turbo_confirm: 'Are you sure you want to delete this task?' },
                  class: "ml-2 p-2 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full transition duration-200" do %>
      <i class="fas fa-times text-xl" data-testid = "delete-button"></i>
    <% end %>
  </div>
</div>

app/views/quests/edit.html.erb
<% content_for :title, "Editing quest" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing quest</h1>

  <%= render "form", quest: @quest %>

  <%= link_to "Show this quest", @quest, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to quests", quests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/quests/index.html.erb
<% content_for :title, "Quests" %>

<div class="w-full">
  

  <div class="bg-[#4cad99] text-white p-4 flex items-center">
    <span class="flex-grow text-center text-3xl font-bold">My Academy Quest</span> 
  </div>

  
  <div class="relative w-full h-[200px] overflow-hidden">
    <%= image_tag "Bread.JPG", alt: "Banner Image", class: "w-full h-full object-cover" %>
  </div>
  
  <div class="relative mt-[70px] z-10">
    <%= image_tag "me.JPG" ,alt: "Profile",class: "w-45 h-45 rounded-full object-cover border-6 border-white mx-auto" %>
  </div>
  
  <div class='flex flex-col gap-5 pt-5 text-center'>
    <h2 class="text-3xl font-bold text-[#4cad99]">Kankanis Borvornsivamon</h2>
    
    <p class="italic text-gray-700 text-lg">- Farm House Academy -</p>

   
      <%= link_to "My Brag", brag_path, class: "rounded-md border-3 border-yellow-500 md:mx-100 mx-40 px-3.5 py-2.5 bg-white text-yellow-500 hover:bg-white block font-medium transition duration-200" %>
    
  </div>

  <div class="flex flex-row h-0.5 rounded-2xl bg-[#4cad99] my-8 md:mx-60 mx-5"></div> 


  <div class="md:mx-60 mx-10 min-h-[230px] md:min-h-[250px] p-4 bg-gray-50 rounded-2xl shadow-md">
    <%= form_with(model: @new_quest, url: quests_path, class: "relative mb-8") do |form| %>
      <%= form.text_field :name, 
                          placeholder: "Add new quest..",
                          class: "w-full pl-4 pr-12 py-3 border border-gray-300 rounded-md text-lg focus:outline-none focus:border-gray-500 focus:ring-0",
                          required: true %>
      <button type="submit" class="absolute right-0 top-0 h-full w-12 flex items-center justify-center bg-[#4cad99] text-white rounded-r-md text-xl hover:bg-teal-500 transition duration-200">
        <i class="fas fa-plus" data-testid = "add-quest-button"></i>
      </button>
    <% end %>

    

    <% if @new_quest.errors.any? %>
      <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4 text-sm">
        <p><strong><%= pluralize(@new_quest.errors.count, "error") %> prohibited this task from being saved:</strong></p>
        <ul>
          <% @new_quest.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @quests.empty? %>
      <div class="text-center text-gray-500 p-6">
        <p class="text-s font-semibold">No quests found.</p>
        <p class="text-sm font-light italic">Add a new quest to get started!</p>
      </div>
    <% else %>
      <div id="quests" class="space-y-4">
       <% @quest_to_display = @quests.order(:created_at).reverse %>
        <% @quest_to_display.each do |quest| %>
         <%= render quest %>
      <% end %>
      </div>
    <% end %>
   
  </div>

  <footer class="bg-[#4cad99] text-white text-center py-4 mt-8 w-full bottom-0 left-0 z-50 static">
      <p class="text-sm md:text-base">&copy; 2025 Academy Quest. All rights reserved.</p>
  </footer>
</div>

app/views/quests/new.html.erb
<% content_for :title, "New quest" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New quest</h1>

  <%= render "form", quest: @quest %>

  <%= link_to "Back to quests", quests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/quests/show.html.erb
<% content_for :title, "Showing quest" %>

<div class="md:w-2/3 w-full h-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing quest</h1>

  <h2 class="text-2xl mb-4"><%= @quest.name %></h2>
  <p class="text-gray-500 mb-4">Status: <%= @quest.status ? "Completed" : "Pending" %></p>
  <p class="text-gray-500 mb-4">Created at: <%= @quest.created_at.strftime("%B %d, %Y") %></p>
  <p class="text-gray-500 mb-4">Updated at: <%= @quest.updated_at.strftime("%B %d, %Y") %></p>


  <%= link_to "Back to quests", quests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/quests/update.turbo_stream.erb
<%# app/views/quests/update.turbo_stream.erb %>
<%= turbo_stream.replace @quest %> 